spring:
  application:
    name: floor-service
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        globally_quoted_identifiers: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: shop
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 2242

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka1:1111/eureka/,http://eureka2:1112/eureka/


